name: Build

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Dependencies
        run: yarn install

      - name: Build APK
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: https://newsapi.org/v2/
        run: |
          cd android && ./gradlew clean assembleRelease bundleRelease && cd ..

      - name: Upload Artifact AAP
        uses: actions/upload-artifact@v3
        with:
          name: MusalaTask.aab
          path: 'android/app/build/outputs/bundle/release/app-release.aab'

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v3
        with:
          name: MusalaTask.apk
          path: 'android/app/build/outputs/apk/release/app-release.apk'
